### ISSUE TITLE
REVIEW FINAL

### ISSUE THREAD

**Issue by JayjeetAtGithub** [ivotron/popper-canopie-paper#46]
- [x] The main concern I had heard was clarifying this paper with some of the previous papers on Popper.  I think also included references to those previous papers would help.  I think if you can just distinguish what those previous papers discussed and then what this adds, then this would clear things up. You did clearly state things in the contributions section but I think it required a little bit of interpretation about the distinctions.

- [x] A reviewer also suggested referencing another work ck or cq?  That they said was very similar in spirit.

**Comment by JayjeetAtGithub** [comment]
@ivotron Do you think point 1 can go to the related work section or does it deserve a separate section of its own, something like `Popper 2.0 vs Popper 1.x` ?

**Comment by JayjeetAtGithub** [comment]
Or i think this would go in the introductions

**Comment by ivotron** [comment]
for the second item, we can have add it to the section of generic (non-containerized) workflow engines

**Comment by JayjeetAtGithub** [comment]
Okay, thanks

**Comment by ivotron** [comment]
the original popper paper can be mentioned right before the "The contributions of this paper are:"

"Popper is a lightweight .... The current version of Popper represents an evolution of an early version .... "

**Comment by ivotron** [comment]
fixed in f3bfa34
